-- Project Name : StockManagement 
-- Date/Time    : 2022/09/24 9:54:49
-- Author       : ftk10
-- RDBMS Type   : Oracle Database
-- Application  : A5:SQL Mk-2

/*
  << 注意！！ >>
  BackupToTempTable, RestoreFromTempTable疑似命令が付加されています。
  これにより、drop table, create table 後もデータが残ります。
  この機能は一時的に $$TableName のような一時テーブルを作成します。
  この機能は A5:SQL Mk-2でのみ有効であることに注意してください。
*/

-- 地方マスタ
--* BackupToTempTable
DROP TABLE PK_REGION_MST CASCADE CONSTRAINTS;

--* RestoreFromTempTable
CREATE TABLE PK_REGION_MST (
  REGION_ID VARCHAR2(3) NOT NULL
  , REGION_NAME_JP VARCHAR2(100) NOT NULL
  , REGION_NAME_EN VARCHAR2(100)
  , CONSTRAINT PK_REGION_MST_PKC PRIMARY KEY (REGION_ID)
) ;

-- ユーザーマスタ_SAMPLE
--* BackupToTempTable
DROP TABLE PK_USER_MST_SAMPLE CASCADE CONSTRAINTS;

--* RestoreFromTempTable
CREATE TABLE PK_USER_MST_SAMPLE (
  USER_ID VARCHAR2(100) NOT NULL
  , USER_NAME VARCHAR2(100) NOT NULL
  , REGION_ID VARCHAR2(100)
  , USER_ADDRESS VARCHAR2(255)
  , PHONE VARCHAR2(50)
  , CREATE_DATE DATE NOT NULL
  , UPDATE_DATE DATE NOT NULL
  , DELETE_DATE DATE
  , CONSTRAINT PK_USER_MST_SAMPLE_PKC PRIMARY KEY (USER_ID)
) ;

-- ユーザーマスタ
--* BackupToTempTable
DROP TABLE PK_USER_MST CASCADE CONSTRAINTS;

--* RestoreFromTempTable
CREATE TABLE PK_USER_MST (
  USER_ID VARCHAR2(100) NOT NULL
  , USER_NAME VARCHAR2(100) NOT NULL
  , PASSWORD VARCHAR2(30) NOT NULL
  , IP_ADDRESS VARCHAR2(20)
  , USER_PERMISSIONS NUMBER(3,0) NOT NULL
  , CREATE_DATE DATE NOT NULL
  , CREATER VARCHAR2(100) NOT NULL
  , CREATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_DATE DATE NOT NULL
  , UPDATER VARCHAR2(100) NOT NULL
  , UPDATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_COUNT NUMBER(5,0) NOT NULL
  , DELETE_FLAG NUMBER(3,0) NOT NULL
  , CONSTRAINT PK_USER_MST_PKC PRIMARY KEY (USER_ID)
) ;

-- タイプマスタ
--* BackupToTempTable
DROP TABLE PK_TYPE_MST CASCADE CONSTRAINTS;

--* RestoreFromTempTable
CREATE TABLE PK_TYPE_MST (
  TYPE_ID NUMBER(3,0) NOT NULL
  , TYPE_NAME VARCHAR2(30) NOT NULL
  , CREATE_DATE DATE NOT NULL
  , CREATER VARCHAR2(100) NOT NULL
  , CREATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_DATE DATE NOT NULL
  , UPDATER VARCHAR2(100) NOT NULL
  , UPDATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_COUNT NUMBER(5,0) NOT NULL
  , DELETE_FLAG NUMBER(3,0) NOT NULL
  , CONSTRAINT PK_TYPE_MST_PKC PRIMARY KEY (TYPE_ID)
) ;

-- ポケモン図鑑説明文マスタ
--* BackupToTempTable
DROP TABLE PK_POKEDEX_EXPLANATION_MST CASCADE CONSTRAINTS;

--* RestoreFromTempTable
CREATE TABLE PK_POKEDEX_EXPLANATION_MST (
  POKEMON_ID NUMBER(5,0) NOT NULL
  , GENERATION_ID NUMBER(3,0)
  , EXPLANATION_HIRAGANA VARCHAR2(1024)
  , EXPLANATION_KANJI VARCHAR2(1024)
  , CREATE_DATE DATE NOT NULL
  , CREATER VARCHAR2(100) NOT NULL
  , CREATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_DATE DATE NOT NULL
  , UPDATER VARCHAR2(100)
  , UPDATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_COUNT NUMBER(5,0) NOT NULL
  , DELETE_FLAG NUMBER(3,0) NOT NULL
) ;

ALTER TABLE PK_POKEDEX_EXPLANATION_MST ADD CONSTRAINT PK_POKEDEX_EXPLANATION_MST_IX1
  UNIQUE (POKEMON_ID,) ;

-- 世代マスタ
--* BackupToTempTable
DROP TABLE PK_GENERATION_MST CASCADE CONSTRAINTS;

--* RestoreFromTempTable
CREATE TABLE PK_GENERATION_MST (
  GENERATION_ID NUMBER(3,0)
  , GENERATION_NAME VARCHAR2(30)
  , CREATE_DATE DATE NOT NULL
  , CREATER VARCHAR2(100) NOT NULL
  , CREATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_DATE DATE NOT NULL
  , UPDATER VARCHAR2(100)
  , UPDATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_COUNT NUMBER(5,0) NOT NULL
  , DELETE_FLAG NUMBER(3,0) NOT NULL
  , CONSTRAINT PK_GENERATION_MST_PKC PRIMARY KEY (GENERATION_ID)
) ;

ALTER TABLE PK_GENERATION_MST ADD CONSTRAINT PK_GENERATION_MST_IX1
  UNIQUE (,) ;

-- ポケモン図鑑マスタ
--* BackupToTempTable
DROP TABLE PK_POKEDEX_MST CASCADE CONSTRAINTS;

--* RestoreFromTempTable
CREATE TABLE PK_POKEDEX_MST (
  POKEMON_ID NUMBER(5,0) NOT NULL
  , POKEMON_ID_BRANCH NUMBER(3,0)
  , GENERATION_ID NUMBER(3,0)
  , POKEMON_JP_NAME VARCHAR2(100)
  , POKEMON_EN_NAME VARCHAR2(100)
  , TYPE_ID_1 NUMBER(3,0)
  , TYPE_ID_2 NUMBER(3,0)
  , HIT_POINT NUMBER(5,0)
  , ATTACK NUMBER(5,0)
  , DEFENSE NUMBER(5,0)
  , SPECIAL_ATTACK NUMBER(5,0)
  , SPECIAL_DEFENSE NUMBER(5,0)
  , SPEED NUMBER(5,0)
  , HEIGHT NUMBER(10,5)
  , WEIGHT NUMBER(10,5)
  , CREATE_DATE DATE NOT NULL
  , CREATER VARCHAR2(100) NOT NULL
  , CREATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_DATE DATE NOT NULL
  , UPDATER VARCHAR2(100)
  , UPDATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_COUNT NUMBER(5,0) NOT NULL
  , DELETE_FLAG NUMBER(3,0) NOT NULL
) ;

ALTER TABLE PK_POKEDEX_MST ADD CONSTRAINT PK_POKEDEX_MST_IX1
  UNIQUE (POKEMON_ID,POKEMON_ID_BRANCH) ;

ALTER TABLE PK_POKEDEX_MST
  ADD CONSTRAINT PK_POKEDEX_MST_FK1 FOREIGN KEY (TYPE_ID_2) REFERENCES PK_TYPE_MST(TYPE_ID);

ALTER TABLE PK_POKEDEX_EXPLANATION_MST
  ADD CONSTRAINT PK_POKEDEX_EXPLANATION_MST_FK1 FOREIGN KEY (GENERATION_ID) REFERENCES PK_GENERATION_MST(GENERATION_ID);

ALTER TABLE PK_POKEDEX_EXPLANATION_MST
  ADD CONSTRAINT PK_POKEDEX_EXPLANATION_MST_FK2 FOREIGN KEY (POKEMON_ID) REFERENCES PK_POKEDEX_MST(POKEMON_ID);

ALTER TABLE PK_POKEDEX_MST
  ADD CONSTRAINT PK_POKEDEX_MST_FK2 FOREIGN KEY (TYPE_ID_1) REFERENCES PK_TYPE_MST(TYPE_ID);

COMMENT ON TABLE PK_REGION_MST IS '地方マスタ';
COMMENT ON COLUMN PK_REGION_MST.REGION_ID IS '地方ID';
COMMENT ON COLUMN PK_REGION_MST.REGION_NAME_JP IS '地方名_日本語';
COMMENT ON COLUMN PK_REGION_MST.REGION_NAME_EN IS '地方名_英語';

COMMENT ON TABLE PK_USER_MST_SAMPLE IS 'ユーザーマスタ_SAMPLE';
COMMENT ON COLUMN PK_USER_MST_SAMPLE.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN PK_USER_MST_SAMPLE.USER_NAME IS 'ユーザー名';
COMMENT ON COLUMN PK_USER_MST_SAMPLE.REGION_ID IS '地方ID';
COMMENT ON COLUMN PK_USER_MST_SAMPLE.USER_ADDRESS IS 'アドレス';
COMMENT ON COLUMN PK_USER_MST_SAMPLE.PHONE IS '電話番号';
COMMENT ON COLUMN PK_USER_MST_SAMPLE.CREATE_DATE IS '登録日付';
COMMENT ON COLUMN PK_USER_MST_SAMPLE.UPDATE_DATE IS '更新日付';
COMMENT ON COLUMN PK_USER_MST_SAMPLE.DELETE_DATE IS '削除日付';

COMMENT ON TABLE PK_USER_MST IS 'ユーザーマスタ';
COMMENT ON COLUMN PK_USER_MST.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN PK_USER_MST.USER_NAME IS 'ユーザー名';
COMMENT ON COLUMN PK_USER_MST.PASSWORD IS 'パスワード';
COMMENT ON COLUMN PK_USER_MST.IP_ADDRESS IS 'IPアドレス';
COMMENT ON COLUMN PK_USER_MST.USER_PERMISSIONS IS 'ユーザー権限ID';
COMMENT ON COLUMN PK_USER_MST.CREATE_DATE IS '登録日付';
COMMENT ON COLUMN PK_USER_MST.CREATER IS '登録者';
COMMENT ON COLUMN PK_USER_MST.CREATE_PROGRAM IS '登録プログラムID';
COMMENT ON COLUMN PK_USER_MST.UPDATE_DATE IS '更新日付';
COMMENT ON COLUMN PK_USER_MST.UPDATER IS '更新者';
COMMENT ON COLUMN PK_USER_MST.UPDATE_PROGRAM IS '更新プログラムID';
COMMENT ON COLUMN PK_USER_MST.UPDATE_COUNT IS '更新回数';
COMMENT ON COLUMN PK_USER_MST.DELETE_FLAG IS '削除フラグ';

COMMENT ON TABLE PK_TYPE_MST IS 'タイプマスタ';
COMMENT ON COLUMN PK_TYPE_MST.TYPE_ID IS 'タイプID';
COMMENT ON COLUMN PK_TYPE_MST.TYPE_NAME IS 'タイプ名';
COMMENT ON COLUMN PK_TYPE_MST.CREATE_DATE IS '登録日付';
COMMENT ON COLUMN PK_TYPE_MST.CREATER IS '登録者';
COMMENT ON COLUMN PK_TYPE_MST.CREATE_PROGRAM IS '登録プログラムID';
COMMENT ON COLUMN PK_TYPE_MST.UPDATE_DATE IS '更新日付';
COMMENT ON COLUMN PK_TYPE_MST.UPDATER IS '更新者';
COMMENT ON COLUMN PK_TYPE_MST.UPDATE_PROGRAM IS '更新プログラムID';
COMMENT ON COLUMN PK_TYPE_MST.UPDATE_COUNT IS '更新回数';
COMMENT ON COLUMN PK_TYPE_MST.DELETE_FLAG IS '削除フラグ';

COMMENT ON TABLE PK_POKEDEX_EXPLANATION_MST IS 'ポケモン図鑑説明文マスタ';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.POKEMON_ID IS 'ポケモンID';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.GENERATION_ID IS '世代ID';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.EXPLANATION_HIRAGANA IS '説明文_ひらがな';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.EXPLANATION_KANJI IS '説明文_漢字';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.CREATE_DATE IS '登録日付';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.CREATER IS '登録者';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.CREATE_PROGRAM IS '登録プログラムID';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.UPDATE_DATE IS '更新日付';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.UPDATER IS '更新者';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.UPDATE_PROGRAM IS '更新プログラムID';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.UPDATE_COUNT IS '更新回数';
COMMENT ON COLUMN PK_POKEDEX_EXPLANATION_MST.DELETE_FLAG IS '削除フラグ';

COMMENT ON TABLE PK_GENERATION_MST IS '世代マスタ';
COMMENT ON COLUMN PK_GENERATION_MST.GENERATION_ID IS '世代ID';
COMMENT ON COLUMN PK_GENERATION_MST.GENERATION_NAME IS '世代名';
COMMENT ON COLUMN PK_GENERATION_MST.CREATE_DATE IS '登録日付';
COMMENT ON COLUMN PK_GENERATION_MST.CREATER IS '登録者';
COMMENT ON COLUMN PK_GENERATION_MST.CREATE_PROGRAM IS '登録プログラムID';
COMMENT ON COLUMN PK_GENERATION_MST.UPDATE_DATE IS '更新日付';
COMMENT ON COLUMN PK_GENERATION_MST.UPDATER IS '更新者';
COMMENT ON COLUMN PK_GENERATION_MST.UPDATE_PROGRAM IS '更新プログラムID';
COMMENT ON COLUMN PK_GENERATION_MST.UPDATE_COUNT IS '更新回数';
COMMENT ON COLUMN PK_GENERATION_MST.DELETE_FLAG IS '削除フラグ';

COMMENT ON TABLE PK_POKEDEX_MST IS 'ポケモン図鑑マスタ';
COMMENT ON COLUMN PK_POKEDEX_MST.POKEMON_ID IS 'ポケモンID';
COMMENT ON COLUMN PK_POKEDEX_MST.POKEMON_ID_BRANCH IS 'ポケモンID枝番';
COMMENT ON COLUMN PK_POKEDEX_MST.GENERATION_ID IS '世代ID';
COMMENT ON COLUMN PK_POKEDEX_MST.POKEMON_JP_NAME IS 'ポケモン日本語名';
COMMENT ON COLUMN PK_POKEDEX_MST.POKEMON_EN_NAME IS 'ポケモン英語名';
COMMENT ON COLUMN PK_POKEDEX_MST.TYPE_ID_1 IS 'タイプID_1';
COMMENT ON COLUMN PK_POKEDEX_MST.TYPE_ID_2 IS 'タイプID_2';
COMMENT ON COLUMN PK_POKEDEX_MST.HIT_POINT IS 'HP';
COMMENT ON COLUMN PK_POKEDEX_MST.ATTACK IS 'こうげき';
COMMENT ON COLUMN PK_POKEDEX_MST.DEFENSE IS 'ぼうぎょ';
COMMENT ON COLUMN PK_POKEDEX_MST.SPECIAL_ATTACK IS 'とっこう';
COMMENT ON COLUMN PK_POKEDEX_MST.SPECIAL_DEFENSE IS 'とくぼう';
COMMENT ON COLUMN PK_POKEDEX_MST.SPEED IS 'すばやさ';
COMMENT ON COLUMN PK_POKEDEX_MST.HEIGHT IS '高さ(m)';
COMMENT ON COLUMN PK_POKEDEX_MST.WEIGHT IS '重さ(kg)';
COMMENT ON COLUMN PK_POKEDEX_MST.CREATE_DATE IS '登録日付';
COMMENT ON COLUMN PK_POKEDEX_MST.CREATER IS '登録者';
COMMENT ON COLUMN PK_POKEDEX_MST.CREATE_PROGRAM IS '登録プログラムID';
COMMENT ON COLUMN PK_POKEDEX_MST.UPDATE_DATE IS '更新日付';
COMMENT ON COLUMN PK_POKEDEX_MST.UPDATER IS '更新者';
COMMENT ON COLUMN PK_POKEDEX_MST.UPDATE_PROGRAM IS '更新プログラムID';
COMMENT ON COLUMN PK_POKEDEX_MST.UPDATE_COUNT IS '更新回数';
COMMENT ON COLUMN PK_POKEDEX_MST.DELETE_FLAG IS '削除フラグ';

