-- Project Name : StockManagement 
-- Date/Time    : 2022/07/15 18:11:47
-- Author       : ftk10
-- RDBMS Type   : Oracle Database
-- Application  : A5:SQL Mk-2

/*
  << 注意！！ >>
  BackupToTempTable, RestoreFromTempTable疑似命令が付加されています。
  これにより、drop table, create table 後もデータが残ります。
  この機能は一時的に $$TableName のような一時テーブルを作成します。
  この機能は A5:SQL Mk-2でのみ有効であることに注意してください。
*/

-- タイプマスタ
--* BackupToTempTable
DROP TABLE PK_TYPE_MST CASCADE CONSTRAINTS;

--* RestoreFromTempTable
CREATE TABLE PK_TYPE_MST (
  TYPE_ID NUMBER(3,0) NOT NULL
  , TYPE_NAME VARCHAR2(30) NOT NULL
  , CREATE_DATE DATE NOT NULL
  , CREATER VARCHAR2(100) NOT NULL
  , CREATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_DATE DATE NOT NULL
  , UPDATER VARCHAR2(100) NOT NULL
  , UPDATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_COUNT NUMBER(5,0) NOT NULL
  , DELETE_FLAG NUMBER(3,0) NOT NULL
  , CONSTRAINT PK_TYPE_MST_PKC PRIMARY KEY (TYPE_ID)
) ;

-- ユーザーマスタ
--* BackupToTempTable
DROP TABLE PK_USER_MST CASCADE CONSTRAINTS;

--* RestoreFromTempTable
CREATE TABLE PK_USER_MST (
  USER_ID VARCHAR2(100) NOT NULL
  , USER_NAME VARCHAR2(100) NOT NULL
  , PASSWORD VARCHAR2(30) NOT NULL
  , IP_ADDRESS VARCHAR2(20)
  , USER_PERMISSIONS NUMBER(3,0) NOT NULL
  , CREATE_DATE DATE NOT NULL
  , CREATER VARCHAR2(100) NOT NULL
  , CREATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_DATE DATE NOT NULL
  , UPDATER VARCHAR2(100) NOT NULL
  , UPDATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_COUNT NUMBER(5,0) NOT NULL
  , DELETE_FLAG NUMBER(3,0) NOT NULL
  , CONSTRAINT PK_USER_MST_PKC PRIMARY KEY (USER_ID)
) ;

-- ポケモン図鑑マスタ
--* BackupToTempTable
DROP TABLE PK_POKEDEX_MST CASCADE CONSTRAINTS;

--* RestoreFromTempTable
CREATE TABLE PK_POKEDEX_MST (
  POKEMON_ID NUMBER(5,0) NOT NULL
  , POKEMON_ID_BRANCH NUMBER(3,0)
  , POKEMON_JP_NAME VARCHAR2(100)
  , POKEMON_EN_NAME VARCHAR2(100)
  , TYPE_ID NUMBER(3,0)
  , HEIGHT NUMBER(10,5)
  , WEIGHT NUMBER(10,5)
  , CREATE_DATE DATE NOT NULL
  , CREATER VARCHAR2(100) NOT NULL
  , CREATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_DATE DATE NOT NULL
  , UPDATER VARCHAR2(100)
  , UPDATE_PROGRAM VARCHAR2(10) NOT NULL
  , UPDATE_COUNT NUMBER(5,0) NOT NULL
  , DELETE_FLAG NUMBER(3,0) NOT NULL
) ;

ALTER TABLE PK_POKEDEX_MST ADD CONSTRAINT PK_POKEDEX_MST_IX1
  UNIQUE (POKEMON_ID,POKEMON_ID_BRANCH) ;

ALTER TABLE PK_POKEDEX_MST
  ADD CONSTRAINT PK_POKEDEX_MST_FK1 FOREIGN KEY (TYPE_ID) REFERENCES PK_TYPE_MST(TYPE_ID);

COMMENT ON TABLE PK_TYPE_MST IS 'タイプマスタ';
COMMENT ON COLUMN PK_TYPE_MST.TYPE_ID IS 'タイプID';
COMMENT ON COLUMN PK_TYPE_MST.TYPE_NAME IS 'タイプ名';
COMMENT ON COLUMN PK_TYPE_MST.CREATE_DATE IS '登録日付';
COMMENT ON COLUMN PK_TYPE_MST.CREATER IS '登録者';
COMMENT ON COLUMN PK_TYPE_MST.CREATE_PROGRAM IS '登録プログラムID';
COMMENT ON COLUMN PK_TYPE_MST.UPDATE_DATE IS '更新日付';
COMMENT ON COLUMN PK_TYPE_MST.UPDATER IS '更新者';
COMMENT ON COLUMN PK_TYPE_MST.UPDATE_PROGRAM IS '更新プログラムID';
COMMENT ON COLUMN PK_TYPE_MST.UPDATE_COUNT IS '更新回数';
COMMENT ON COLUMN PK_TYPE_MST.DELETE_FLAG IS '削除フラグ';

COMMENT ON TABLE PK_USER_MST IS 'ユーザーマスタ';
COMMENT ON COLUMN PK_USER_MST.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN PK_USER_MST.USER_NAME IS 'ユーザー名';
COMMENT ON COLUMN PK_USER_MST.PASSWORD IS 'パスワード';
COMMENT ON COLUMN PK_USER_MST.IP_ADDRESS IS 'IPアドレス';
COMMENT ON COLUMN PK_USER_MST.USER_PERMISSIONS IS 'ユーザー権限ID';
COMMENT ON COLUMN PK_USER_MST.CREATE_DATE IS '登録日付';
COMMENT ON COLUMN PK_USER_MST.CREATER IS '登録者';
COMMENT ON COLUMN PK_USER_MST.CREATE_PROGRAM IS '登録プログラムID';
COMMENT ON COLUMN PK_USER_MST.UPDATE_DATE IS '更新日付';
COMMENT ON COLUMN PK_USER_MST.UPDATER IS '更新者';
COMMENT ON COLUMN PK_USER_MST.UPDATE_PROGRAM IS '更新プログラムID';
COMMENT ON COLUMN PK_USER_MST.UPDATE_COUNT IS '更新回数';
COMMENT ON COLUMN PK_USER_MST.DELETE_FLAG IS '削除フラグ';

COMMENT ON TABLE PK_POKEDEX_MST IS 'ポケモン図鑑マスタ';
COMMENT ON COLUMN PK_POKEDEX_MST.POKEMON_ID IS 'ポケモンID';
COMMENT ON COLUMN PK_POKEDEX_MST.POKEMON_ID_BRANCH IS 'ポケモンID枝番';
COMMENT ON COLUMN PK_POKEDEX_MST.POKEMON_JP_NAME IS 'ポケモン日本語名';
COMMENT ON COLUMN PK_POKEDEX_MST.POKEMON_EN_NAME IS 'ポケモン英語名';
COMMENT ON COLUMN PK_POKEDEX_MST.TYPE_ID IS 'タイプID';
COMMENT ON COLUMN PK_POKEDEX_MST.HEIGHT IS '高さ';
COMMENT ON COLUMN PK_POKEDEX_MST.WEIGHT IS '重さ';
COMMENT ON COLUMN PK_POKEDEX_MST.CREATE_DATE IS '登録日付';
COMMENT ON COLUMN PK_POKEDEX_MST.CREATER IS '登録者';
COMMENT ON COLUMN PK_POKEDEX_MST.CREATE_PROGRAM IS '登録プログラムID';
COMMENT ON COLUMN PK_POKEDEX_MST.UPDATE_DATE IS '更新日付';
COMMENT ON COLUMN PK_POKEDEX_MST.UPDATER IS '更新者';
COMMENT ON COLUMN PK_POKEDEX_MST.UPDATE_PROGRAM IS '更新プログラムID';
COMMENT ON COLUMN PK_POKEDEX_MST.UPDATE_COUNT IS '更新回数';
COMMENT ON COLUMN PK_POKEDEX_MST.DELETE_FLAG IS '削除フラグ';

